import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Playfair_Display, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({ subsets: ['latin'], weight: '400', display: 'swap' });
const playfairDisplay = Playfair_Display({ subsets: ['latin'], weight: '400', display: 'swap' });
const robotoSlab = Roboto_Slab({ subsets: ['latin'], weight: '400', display: 'swap' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} ${playfairDisplay.className} ${robotoSlab.className} antialiased`} suppressHydrationWarning
      >
        <Providers>
        {children}
        </Providers>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
